name: Docker Publish

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 4 1 * *'
  workflow_dispatch:

env:
  IMAGE_NAME: cloudflare-dns-api
  GITHUB_REGISTRY: ghcr.io
  DOTNET_SDK_VERSION: 9.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - uses: dotnet/nbgv@master
      with:
        setAllVars: true
      id: nbgv

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3 # Use a specific stable version
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

    - name: Versioning - Update projects
      run: |
        echo ${{ steps.nbgv.outputs.SemVer2 }}
        echo "Installing tool dotnet-setversion"
        dotnet tool install -g dotnet-setversion
        echo "Setting version for projects"
        setversion --recursive ${{ steps.nbgv.outputs.SemVer2 }}

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3 # Use a specific stable version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # Use a specific stable version

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5 # Use a specific stable version
      with:
        images: |
          ${{ env.GITHUB_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}},priority=900,prefix=,suffix=.${{ github.run_number }},enable=${{ github.ref == 'refs/heads/main' }},value=${{ steps.nbgv.outputs.SimpleVersion }}
          type=semver,pattern={{version}},priority=900,prefix=rc-,suffix=.${{ github.run_number }},enable=${{ github.ref != 'refs/heads/main' }},value=${{ steps.nbgv.outputs.SimpleVersion }}
          type=semver,pattern={{major}}.{{minor}},priority=825,prefix=,suffix=,enable=${{ github.ref == 'refs/heads/main' }},value=${{ steps.nbgv.outputs.SimpleVersion }}
          type=semver,pattern={{major}}.{{minor}},priority=825,prefix=rc-,suffix=,enable=${{ github.ref != 'refs/heads/main' }},value=${{ steps.nbgv.outputs.SimpleVersion }}
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
        flavor: |
          latest=false

    - name: Log into GHCR
      uses: docker/login-action@v3 # Use a specific stable version
      with:
        registry: ${{ env.GITHUB_REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event_name != 'pull_request' }}

    - name: Build and push to GHCR
      uses: docker/build-push-action@v5 # Use a specific stable version
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        registry: ${{ env.GITHUB_REGISTRY }}
        repository: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}